#!/usr/bin/env bash

# none of these need to be functions
# you could probably do this in one line if you really wanted to

download_lists() {
	echo "downloading list sources ..."
	echo -e "\tthis may take some time"
	mkdir .monolith
	wget --directory-prefix=.monolith --input-file=lists --quiet --show-progress
	echo -e "\t- done\n"
}

download_lists

cat_lists() {
	echo "combining list sources ..."
	cat .monolith/* > raw_list
	echo -e "\t- done\n"
}

cat_lists

sort_list() {
	echo "sorting combined list ..."
	echo -e "\tthis may take some time"
	sort -b -u raw_list > sorted_list
	echo -e "\t- done\n"
}

sort_list

strip_list() {
	echo "stripping comments from sorted list ..."
	echo -e "\tthis may take some time"
	sed '/^#/ d' < sorted_list > monolithic_list
	echo -e "\t- done\n"
}

strip_list

cleanup() {
	echo "removing unneeded files ..."
	if [ -d .monolith ]; then
		rm -f .monolith
	fi
	if [ -f raw_list ]; then
		rm raw_list
	fi
	if [ -f sorted_list]; then
		rm sorted_list
	fi
	echo -e "\t- done\n"
}

cleanup
