#!/usr/bin/env bash

# none of these need to be functions
# you could probably do this in one line if you really wanted to

download_lists() {
	echo "downloading lists ..."
	echo -e "\tthis may take some time"
	mkdir .monolith
	wget --directory-prefix=.monolith --input-file=lists --quiet --show-progress
	echo -e "\t- done\n"
}

download_lists

cat_lists() {
	echo "combining lists ..."
	cat .monolith/* > .monolith/raw_list
	echo -e "\t- done\n"
}

cat_lists

sort_list() {
	echo "sorting combined list ..."
	echo -e "\tthis may take some time"
	sort -b -u .monolith/raw_list > .monolith/sorted_list
	echo -e "\t- done\n"
}

sort_list

strip_list() {
	echo "stripping sorted list ..."
	echo -e "\tthis may take some time"
	sed -e "/^#/ d" -e "s/^0.0.0.0 //" -e "s/^0.0.0.0     //" -e "s/0.0.0.0//" -e "s/^127.0.0.1 //" -e "s/127.0.0.1    //" -e "s/127.0.0.1//" < .monolith/sorted_list > monolithic_list
	echo -e "\t- done\n"
}

strip_list

cleanup() {
	echo "removing unneeded files ..."
	if [ -d .monolith ]; then
		rm -r .monolith
	fi
	echo -e "\t- done\n"
}

cleanup
